config/routes.rb
Code::Application.routes.draw do
  resources :snippets
  root :to => "snippets#new"
  mount Resque::Server, :at => "/resque"
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :highlighted_code, :language, :name, :plain_code
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snippets }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.json
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/1/edit
  def edit
    @snippet = Snippet.find(params[:id])
  end


  def create
  @snippet = Snippet.new(params[:snippet])

  respond_to do |format|
    if @snippet.save
      format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
      format.json { render json: @snippet, status: :created, location: @snippet }
    else
      format.html { render action: "new" }
      format.json { render json: @snippet.errors, status: :unprocessable_entity }
    end
  end
end

  # PUT /snippets/1
  # PUT /snippets/1.json
  def update
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Snippets</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="divider-vertical"></li>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Filter  <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">CSS</a></li>
            <li><a href="#">HTML</a></li>
            <li><a href="#">JS</a></li>
            <li><a href="#">Ruby</a></li>
            <li><a href="#">Markdown</a></li>
            <li><a href="#">PHP</a></li>
            <li><a href="#">Apache</a></li>
            <li><a href="#">Nginx</a></li>
          </ul>
          <li class="divider-vertical"></li>
          <li><i class="icon-plus"></i><%= link_to 'Snippet', new_snippet_path, :class => 'add-snippet' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>  
<div class="container">
  <div class="row-fluid">
    <div class="span12">
        <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'text_field', :placeholder => 'Snippet Name' %>
  </div>
  <div class="field">
    <%= f.label :language %>
    <%= f.select :language, options_for_select([["CSS", "css"],["HTML", "html"], ["JavaScript", "javascript"],["Ruby", "ruby"],["Markdown","markdown"],["PHP","php"],["Apache","apache"],["Nginx","nginx"]]) %>
  </div>
  <div class="field">
    <%= f.label :plain_code, "Source Code" %>
    <%= f.text_area :plain_code, :rows => '7' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn-large btn-primary' %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<% @snippets.each do |snippet| %>
<div class="snippet span3">
<h3 class="copy-snippet"><%= snippet.name %></h3>
  <p><%= snippet.language %></p>
  <pre><code class="clippy"><%= snippet.plain_code %></code></pre>
    <%= link_to 'Show', snippet %>
    <%= link_to 'Edit', edit_snippet_path(snippet) %>
    <%= link_to 'Destroy', snippet, confirm: 'Are you sure?', method: :delete %>
</div>
<% end %>

app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p>
  <strong>Language:</strong>
  <%= @snippet.language.titleize %>
</p>
<div class="code_block">
  <% if @snippet.highlighted_code.present? %>
    <%= raw @snippet.highlighted_code %>
  <% else %>
    <pre><%= @snippet.plain_code %></pre>
  <% end %>
</div>

<p>
  <%= link_to "New Snippet", new_snippet_path %>
</p>
<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>